rpc: check dust outputs on account withdrawals and closures
lightninglabs/pool pull request #150
Opened 2020-11-09 22:16 UTC by wpaulino

Prevents https://github.com/lightninglabs/pool/issues/146 from happening.

2020-11-10 00:08 UTC, Roasbeef requested changes

2020-11-10 00:08 UTC, Roasbeef commented on rpcserver.go
> +		if txrules.IsDustOutput(txOut, txrules.DefaultRelayFeePerKb) {
Perhaps we should move this check further into the pipeline (within the account manager) so we can bolster things with some additional unit tests?

2020-11-11 21:34 UTC, Roasbeef approved these changes
LGTM 🥮

2020-11-12 01:48 UTC, Roasbeef commented on account/manager_test.go
> +	dustOutput := &wire.TxOut{Value: 0, PkScript: p2wsh}
👍

2020-11-12 07:59 UTC, halseth approved these changes
LGTM 👍

2020-11-12 07:59 UTC, merged