cmd/poold: pprof listen on localhost
lightninglabs/pool pull request #228
Opened 2021-03-02 22:23 UTC by Crypt-iQ

Otherwise, debugging information is exposed if the port is reachable.

2021-03-05 08:56 UTC, halseth requested changes

2021-03-05 08:56 UTC, halseth commented on cmd/poold/main.go
> +			listenAddr := net.JoinHostPort("127.0.0.1", config.Profile)
there are very valid use case for allowing profiling on a externally reachable port though.  Could we make the `config.Profile` option optionally set this IP?

2021-03-05 09:17 UTC, guggero requested changes
:+1: for making this configurable. How about this: We change the `config.Profile` to a string and parse it. If it's just a number (e.g. to not break existing users that have the flag set), we use `127.0.0.1` as the host. If it's a `host:port` pair, use that directly.
Same for the other repos where this was proposed.

2021-12-07 12:43 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers for your latest update

2021-12-10 13:27 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers for your latest update

2021-12-13 13:33 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers for your latest update

2021-12-16 13:39 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers for your latest update

2021-12-23 14:21 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2021-12-30 15:04 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-01-06 15:56 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-01-13 16:45 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-01-20 17:38 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-01-27 17:39 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-02-03 18:36 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-02-17 19:32 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-02-24 19:50 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-03-03 20:38 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-03-21 18:33 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-03-28 18:36 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-04-04 19:12 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-04-11 19:29 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-04-18 19:32 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-04-25 20:26 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-05-02 21:17 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-05-09 21:32 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-05-16 22:14 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-05-23 22:22 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-05-30 22:46 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-06-06 23:17 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-06-13 23:46 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-06-20 23:55 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-06-27 23:56 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-07-05 00:11 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-07-18 21:13 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-07-25 21:47 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-07-29 01:04 UTC, Misuwp approved these changes

2022-08-05 01:58 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-08-12 02:46 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-08-19 03:29 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-08-26 04:18 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-09-02 05:05 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-09-09 05:56 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-09-16 06:04 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-09-23 06:25 UTC, lightninglabs-deploy commented
@crypt-iq, remember to re-request review from reviewers when ready

2022-09-23 07:46 UTC, guggero commented
Replaced by https://github.com/lightninglabs/pool/pull/391.

2022-09-23 07:46 UTC, closed without merging