rpc: populate allowed/not allowed node ids when listing orders
lightninglabs/pool pull request #429
Opened 2023-01-05 09:17 UTC by positiveblue

Fixes #428 
Depends on #427

2023-01-05 09:51 UTC, guggero requested changes

2023-01-05 12:26 UTC, positiveblue commented on rpcserver.go
> +			allowedNodeIDs = append(allowedNodeIDs, nodeID[:])
Right, tests added for it :+1:

To have this done everywhere with the same structure we could have a `serialize.go` in each package that has the logic to serialize/deserialize obj from/to rpc and `rpcserver.go` calls those. In that way we can keep the testing (with invalid inputs) in the package itself. Similar to the current `rpc_parse.go` in orders but without splitting the logic between that file and the `rpcserver.go`.

2023-01-05 12:41 UTC, guggero approved these changes

2023-01-05 12:41 UTC, guggero commented on order/rpc_parse.go
> +func UnmarshalNodeIDSlice(slice [][]byte) ([][33]byte, error) {
Nice! We can re-use this on the server side as well.

2023-01-05 12:41 UTC, guggero commented on order/rpc_parse.go
> +// MarshalNodeIDSlice returns a flatten version of an slice of node ids to be
nit: s/flatten/flattened/

2023-01-06 11:21 UTC, guggero commented on tools/Dockerfile
> +  # The last line is needed to ensure that go build is able to gather
Can be removed.

2023-01-06 16:34 UTC, positiveblue commented on tools/Dockerfile
> +  && chmod -R 777 /tmp/build/
reverts a commit that I pushed by error in #426

2023-01-06 17:12 UTC, jbrill approved these changes
LGTM 👍 very comprehensive tests. I was unable to get the fields showing in an end to end test as it looks like there's some additional field marshaling we need to do subasta-side.

2023-01-09 07:33 UTC, merged