build: update to build against lnd v0.17.0
lightninglabs/pool pull request #465
Opened 2023-08-24 23:14 UTC by Roasbeef

In this commit, we update the project to build against lnd v0.17.0. The `lnwire` signature parsing routines were changed, so we update all the relevant call sites to use the new functions.

Due to [this
PR](https://github.com/lightningnetwork/lnd/pull/7659/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R183), we now need to inherit the replace directive set, otherwise this build fails. IIUC, this now goes for any other project that uses the `lnrpc` package. We may want to reconsider the replace for lnd now that we're in the rc process.

2023-08-25 16:22 UTC, positiveblue commented
Some unit tests need to be updated `error storing sidecar ticket: malformed signature: too short: 71 bytes`

Should we bump `lndclient` first  and update it in this PR too?

2023-08-28 08:30 UTC, guggero requested changes

2023-08-28 08:30 UTC, guggero commented on go.mod
> +replace google.golang.org/protobuf => github.com/lightninglabs/protobuf-go-hex-display v1.30.0-hex-display
Should we also add the reason for the replace as a comment? See https://github.com/lightninglabs/taproot-assets/blob/main/go.mod#L208

And yes, unfortunately we need this replace in every project now... But at least we can remove the other one for `google.golang.org/grpc` if we update to the latest Aperture version.

2023-09-04 08:59 UTC, lightninglabs-deploy commented
@roasbeef, remember to re-request review from reviewers when ready

2023-09-11 09:24 UTC, lightninglabs-deploy commented
@roasbeef, remember to re-request review from reviewers when ready

2023-09-18 10:03 UTC, lightninglabs-deploy commented
@roasbeef, remember to re-request review from reviewers when ready

2023-09-18 19:16 UTC, Roasbeef commented
Refreshed!

2023-09-19 07:10 UTC, guggero commented on sidecar/tlv.go
> +			sig, err := lnwire.NewSigFromWireECDSA(rawSig)
Also need to use `NewSigFromECDSARawSignature` here.

2023-09-19 07:10 UTC, guggero commented on sidecar/tlv.go
> +			wireSig, err := lnwire.NewSigFromWireECDSA(s[:])
Also need to use `NewSigFromECDSARawSignature` here.

2023-09-22 16:57 UTC, guggero commented
Replaced by https://github.com/lightninglabs/pool/pull/468.

2023-09-22 16:57 UTC, closed without merging